version: '3.8'

services:
  dbpostgresql:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=micronaut
    ports:
      - "5432:5432"
    networks:
      - micronaut_net

networks:
  micronaut_net:
