name: Publish to Bintray

on:
  watch:
    types: [started]

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Publish v${{ github.ref }} to Bintry
        env:
          bintrayUser: ${{ secrets.BINTRAY_USER }}
          bintrayApiKey: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew clean build bintrayUpload
