on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create a new release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            Changes in this release
            - ...
            - ...
          draft: false
          prerelease: false
