on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create a new release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release
            - have all methods in CRUDService public now
            - fixed bug while getting generic type arguments
          draft: false
          prerelease: false
